name: Update Submodule Links

on: [push]

jobs:
  update-links:
    if: ${{ !contains(github.event.head_commit.message, 'automatic update of submodule links') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACTIONS_PAT }}
          
      - name: Update submodule links in markdown files
        uses: pablofl01/replace-submodule-paths@v1.1.1
        with:
          file_pattern: "**/*.md"
          
      - uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "docs: automatic update of submodule links"